# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1447938544);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1447938664);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1448016763);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1447938424);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1448016643);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "NL");
user_pref("browser.search.region", "NL");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20151104030705");
user_pref("browser.slowStartup.averageTime", 619);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage", "http://localhost:7001/console/console.portal?_nfpb=true&_pageLabel=CoreServerServerTablePage");
user_pref("browser.startup.homepage_override.buildID", "20151104030705");
user_pref("browser.startup.homepage_override.mstone", "38.4.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3,\"bookmarks\":0}");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[],\"dirtyAreaCache\":[\"addon-bar\",\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":4,\"newElementCount\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1448019999821");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1448019999821");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1447938125255");
user_pref("datareporting.policy.firstRunTime", "1447938064217");
user_pref("datareporting.sessions.current.activeTicks", 308);
user_pref("datareporting.sessions.current.firstPaint", 560);
user_pref("datareporting.sessions.current.main", 50);
user_pref("datareporting.sessions.current.sessionRestored", 645);
user_pref("datareporting.sessions.current.startTime", "1448010942032");
user_pref("datareporting.sessions.current.totalTime", 9057);
user_pref("datareporting.sessions.currentIndex", 6);
user_pref("datareporting.sessions.previous.0", "{\"s\":1447938063810,\"a\":254,\"t\":32835,\"c\":false,\"m\":123,\"fp\":1236,\"sr\":1424}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1448010753001,\"a\":12,\"t\":86,\"c\":true,\"m\":151,\"fp\":921,\"sr\":1021}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1448010840866,\"a\":1,\"t\":2,\"c\":true,\"m\":41,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1448010852922,\"a\":8,\"t\":52,\"c\":true,\"m\":51,\"fp\":465,\"sr\":599}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1448010915920,\"a\":4,\"t\":15,\"c\":true,\"m\":40,\"fp\":498,\"sr\":640}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1448010932810,\"a\":1,\"t\":2,\"c\":true,\"m\":51,\"fp\":-1,\"sr\":-1}");
user_pref("dom.disable_open_during_load", false);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.4.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1447938545);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.4.0");
user_pref("extensions.lastPlatformVersion", "38.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.4.0\",\"st\":1447794892000,\"mt\":1446636483000}}}");
user_pref("gecko.buildID", "20151104030705");
user_pref("gecko.mstone", "38.4.0");
user_pref("idle.lastDailyNotification", 1447938383);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1447938127);
user_pref("media.gmp-gmpopenh264.version", "1.4");
user_pref("media.gmp-manager.buildID", "20151104030705");
user_pref("media.gmp-manager.lastCheck", 1447938126);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1447938383);
user_pref("places.history.expiration.transient_current_max_pages", 46453);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.browser.homepage.disable_button.bookmark_page", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1447938383);
user_pref("toolkit.startup.last_success", 1448010942);
user_pref("toolkit.telemetry.previousBuildID", "20151104030705");
